-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 17:00:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crm_trial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crm_trial` ;

-- -----------------------------------------------------
-- Schema crm_trial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm_trial` DEFAULT CHARACTER SET utf8 ;
USE `crm_trial` ;

-- -----------------------------------------------------
-- Table `crm_trial`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crm_trial`.`Users` ;

CREATE TABLE IF NOT EXISTS `crm_trial`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `UserRole` VARCHAR(45) NOT NULL DEFAULT 'Guest',
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_trial`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crm_trial`.`Comments` ;

CREATE TABLE IF NOT EXISTS `crm_trial`.`Comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `ReviewText` VARCHAR(45) NOT NULL,
  `ReviewRating` INT NOT NULL,
  PRIMARY KEY (`comment_id`, `UserID`),
  INDEX `UserID` (`UserID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `crm_trial`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
